version: "3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik"
    restart: always
    command:
      - "--log.level=ERROR"
      # - "--api=true"
      # - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=my_network"
      - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment when debugging SSL issues
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  traefik_acme:
